from pathlib import Path

p=Path('src/utils/offerPdf.ts')
s=p.read_text()
s=s.replace("async function renderHtmlPagesToPdf(\n  html: string,\n  fileName: string,\n  backgroundColor: string,\n)", "async function renderHtmlPagesToPdf(\n  html: string,\n  fileName: string,\n  backgroundColor: string,\n  save = true,\n)")
s=s.replace("    saveBlobDownload(\n      pdf.output(\n        'blob',\n      ),\n      fileName,\n    )", "    const blob = pdf.output(\n      'blob',\n    )\n\n    if (save) {\n      saveBlobDownload(\n        blob,\n        fileName,\n      )\n    }\n\n    return blob")
anchor="export async function downloadOfferPdf(\n"
idx=s.index(anchor)
helper="""export async function createOfferPdfBlob(\n  data: OfferPdfData,\n  customSettings:\n    Partial<OfferPdfSettings> = {},\n) {\n  const pricedOffer =\n    await resolveOfferPricing(data)\n  const settings =\n    await prepareOfferPdfSettings(\n      pricedOffer,\n      customSettings,\n    )\n  const html = buildOfferPdfHtml(\n    pricedOffer,\n    settings,\n  )\n  const fileName =\n    `${safeFileName(data.offerNumber || 'Ponuda')}-${safeFileName(data.customerName || 'Investitor')}.pdf`\n  const blob = await renderHtmlPagesToPdf(\n    html,\n    fileName,\n    settings.backgroundColor || '#FFFFFF',\n    false,\n  )\n  if (!blob) throw new Error('PDF ponude nije moguće izraditi.')\n  return { blob, fileName }\n}\n\n"""
s=s[:idx]+helper+s[idx:]
p.write_text(s)

p=Path('src/pages/NewOfferPage.tsx')
s=p.read_text()
s=s.replace("import { downloadOfferPdf } from '../utils/offerPdf'", "import { createOfferPdfBlob, downloadOfferPdf } from '../utils/offerPdf'\nimport { Capacitor } from '@capacitor/core'")
start=s.index('async function openOfferEmailDraft(')
end=s.index('\nexport function NewOfferPage()', start)
new="""async function openOfferEmailDraft(\n  offer: Offer,\n  company: CompanySettings,\n  globalDiscount = 0,\n) {\n  const recipient = offer.email.trim()\n  if (!recipient) {\n    window.alert('Ponuda je spremljena, ali investitor nema unesenu e-mail adresu.')\n    return\n  }\n\n  const safeGlobalDiscount = Math.min(100, Math.max(0, Number(globalDiscount) || 0))\n  const globalFactor = 1 - safeGlobalDiscount / 100\n  const total = offer.items.reduce((sum, item) => {\n    const net = calculateItemNet(item) * globalFactor\n    return sum + net + net * (item.vat / 100)\n  }, 0)\n  const formattedTotal = new Intl.NumberFormat('hr-HR', {\n    style: 'currency', currency: company.currency || 'EUR',\n  }).format(total)\n  const formattedValidUntil = offer.validUntil\n    ? new Date(`${offer.validUntil}T12:00:00`).toLocaleDateString('hr-HR')\n    : 'nije navedeno'\n  const companyName = company.name.trim() || 'Tvrtka'\n  const subject = `Ponuda ${offer.offerNumber} – ${companyName}`\n  const body = [\n    `Poštovani/a ${offer.customerName},`, '',\n    `dostavljamo Vam ponudu broj ${offer.offerNumber}.`, '',\n    `Ponuda vrijedi do ${formattedValidUntil}.`,\n    `Ukupan iznos ponude: ${formattedTotal}.`, '',\n    'PDF ponude nalazi se u privitku ove poruke.', '',\n    'Za dodatne informacije stojimo Vam na raspolaganju.', '',\n    'Lijep pozdrav,', companyName,\n    company.phone ? `Telefon: ${company.phone}` : '',\n    company.email ? `E-mail: ${company.email}` : '',\n  ].filter((line, index, lines) => line !== '' || lines[index - 1] !== '').join('\\n')\n\n  try {\n    const { blob, fileName } = await createOfferPdfBlob(offer)\n\n    if (Capacitor.isNativePlatform()) {\n      const [{ Filesystem, Directory }, { Share }] = await Promise.all([\n        import('@capacitor/filesystem'), import('@capacitor/share'),\n      ])\n      const dataUrl = await new Promise<string>((resolve, reject) => {\n        const reader = new FileReader()\n        reader.onload = () => typeof reader.result === 'string'\n          ? resolve(reader.result.split(',')[1] || '')\n          : reject(new Error('PDF nije moguće pripremiti.'))\n        reader.onerror = () => reject(new Error('PDF nije moguće pripremiti.'))\n        reader.readAsDataURL(blob)\n      })\n      const saved = await Filesystem.writeFile({\n        path: fileName, data: dataUrl, directory: Directory.Cache, recursive: true,\n      })\n      await Share.share({\n        title: subject,\n        text: body,\n        files: [saved.uri],\n        dialogTitle: 'Pošalji ponudu s PDF privitkom',\n      })\n      return\n    }\n\n    downloadOfferPdf(offer)\n    window.location.href = `mailto:${encodeURIComponent(recipient)}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`\n  } catch (error) {\n    window.alert(error instanceof Error ? error.message : 'Ponudu nije moguće pripremiti za slanje.')\n  }\n}\n"""
s=s[:start]+new+s[end:]
p.write_text(s)
print('patched')